
### 获取认证token
GET http://127.0.0.1:8080/auth?username=test&password=test123456

> {%
client.log("====="+response.body.data.token)
client.global.set("auth_token", response.body.data.token);
%}

### 新增标签
POST http://localhost:8080/api/v1/tags?name=2&state=1&created_by=test
Authorization: {{auth_token}}

### 获取标签
GET http://localhost:8080/api/v1/tags?name=1&state=1&created_by=test
Authorization: {{auth_token}}


### add articles
POST http://127.0.0.1:8080/api/v1/articles?tag_id=1&title=test1&desc=test-desc&content=test-content&created_by=test-created&state=1
Authorization: {{auth_token}}

### list articles
GET http://127.0.0.1:8080/api/v1/articles
Authorization: {{auth_token}}

### get article
GET http://127.0.0.1:8080/api/v1/articles/1?token=
Authorization: {{auth_token}}
### PUT article
PUT http://127.0.0.1:8080/api/v1/articles/1?tag_id=1&title=test-edit1&desc=test-desc-edit&content=test-content-edit&modified_by=test-created-edit&state=0
Authorization: {{auth_token}}

### delete article
DELETE http://127.0.0.1:8080/api/v1/articles/1
Authorization: {{auth_token}}




